// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLo0qd-X7wTmGZ5MmDY-xv5N58aTQtIBg',
    appId: '1:411217346388:web:dab40ba2245be3cd2952c1',
    messagingSenderId: '411217346388',
    projectId: 'hungerhub-9ae1f',
    authDomain: 'hungerhub-9ae1f.firebaseapp.com',
    storageBucket: 'hungerhub-9ae1f.firebasestorage.app',
    measurementId: 'G-GTF7BGQLMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASI0B8PEj3dLEOK1i5vcRKgZh67B9WYFA',
    appId: '1:411217346388:android:84b07493f69fe8812952c1',
    messagingSenderId: '411217346388',
    projectId: 'hungerhub-9ae1f',
    storageBucket: 'hungerhub-9ae1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3vHutPcpqqMD2F-8E0vDGZCyXicy4rvk',
    appId: '1:411217346388:ios:ec05338380e97c2d2952c1',
    messagingSenderId: '411217346388',
    projectId: 'hungerhub-9ae1f',
    storageBucket: 'hungerhub-9ae1f.firebasestorage.app',
    iosBundleId: 'com.example.hungerHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3vHutPcpqqMD2F-8E0vDGZCyXicy4rvk',
    appId: '1:411217346388:ios:ec05338380e97c2d2952c1',
    messagingSenderId: '411217346388',
    projectId: 'hungerhub-9ae1f',
    storageBucket: 'hungerhub-9ae1f.firebasestorage.app',
    iosBundleId: 'com.example.hungerHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLo0qd-X7wTmGZ5MmDY-xv5N58aTQtIBg',
    appId: '1:411217346388:web:80c204f90cd92b482952c1',
    messagingSenderId: '411217346388',
    projectId: 'hungerhub-9ae1f',
    authDomain: 'hungerhub-9ae1f.firebaseapp.com',
    storageBucket: 'hungerhub-9ae1f.firebasestorage.app',
    measurementId: 'G-CZT9TRDWZX',
  );
}
